name: POI API .NET Core Workflow

on:
  push:
    branches: [ master ]
    paths:
      - 'apis/poi/**'
      - '.github/workflows/dotnet-core.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'apis/poi/**'
      - '.github/workflows/dotnet-core.yml'


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      workDir: ./apis/poi/
      AZURE_WEBAPP_NAME: openhackrwy2hdr5poi
      CONTAINER_REGISTRY: ${{ secrets.REGISTRY_URL }}  # set secret with Container Registry URL, example : xyz.azurecr.io 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.200
    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Install dependencies
      working-directory: ${{env.workDir}}
      run: dotnet restore
    - name: Build
      working-directory: ${{env.workDir}}
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ${{env.workDir}}/tests/UnitTests/
      run: dotnet test --no-restore --verbosity normal
    - name: Create an issue on failure
      if: ${{ failure() }}
      uses: actions/github-script@v3.0.0
      with:
        # The script to run
        script: |
            let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
              body: body
            });      
    - name: Docker Build
      run: |
        docker build -t ${{ env.CONTAINER_REGISTRY }}/devopsoh/api-poi:${{ github.run_number }} -f ./apis/poi/web/Dockerfile ./apis/poi/web
    - name: ACR authentication
      if: ${{ github.event_name != 'pull_request' }}
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}    
    - name: Docker Build & Push to ACR
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        docker push ${{ env.CONTAINER_REGISTRY }}/devopsoh/api-poi:${{ github.run_number }}    
    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
        images: ${{ env.CONTAINER_REGISTRY }}/devopsoh/api-poi:${{ github.run_number }}
        slot-name: 'staging' 
       
