name: trips API

on:
  push:
    branches: [master]
    paths:
      - 'apis/trips/**'
      - '.github/workflows/trips-api.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'apis/trips/**'
      - '.github/workflows/trips-api.yml'


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      workDir: ./apis/trips/
      CONTAINER_REGISTRY: ${{ secrets.REGISTRY_URL }}  # set secret with Container Registry URL, example : xyz.azurecr.io 
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.11.1' # The Go version to download (if necessary) and use.
    - name: Test
      working-directory: ${{env.workDir}}/tests/
      run: go test
    - name: Create an issue on failure
      if: ${{ failure() }}
      uses: actions/github-script@v3.0.0
      with:
        # The script to run
        script: |
            let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
              body: body
            });      
    - name: Docker Build
      run: |
        docker build -t ${{ env.CONTAINER_REGISTRY }}/devopsoh/api-trips:${{ github.run_number }} -t ${{ env.CONTAINER_REGISTRY }}/devopsoh/api-trips:latest -f ./apis/trips/Dockerfile ./apis/trips
    - name: ACR authentication
      if: ${{ github.event_name != 'pull_request' }}
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}    
    - name: Docker Build & Push to ACR
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        docker push ${{ env.CONTAINER_REGISTRY }}/devopsoh/api-trips:${{ github.run_number }}
        docker push ${{ env.CONTAINER_REGISTRY }}/devopsoh/api-trips:latest
        
       
