# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [vasalis*]
    paths:
      - 'apis/user-java/**'
      - '.github/workflows/UserJavaCI.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'apis/user-java/**'
      - '.github/workflows/UserJavaCI.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      workDir: ./apis/user-java/
      CONTAINER_REGISTRY: ${{ secrets.REGISTRY_URL }}  # set secret with Container Registry URL, example : xyz.azurecr.io 

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      working-directory: ${{env.workDir}}
      run: mvn -B package --file pom.xml
      
    - name: Test with Maven
      working-directory: ${{env.workDir}}
      run: mvn test
